FROM alpine:3.15
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN apk add --update --no-cache git bash gcc build-base libffi-dev openssl-dev bzip2-dev zlib-dev xz-dev readline-dev sqlite-dev
RUN chown -R 1000:1000 /usr/src/app
USER 1000:1000
# TODO: Finish this fresh pyenv build
#RUN /bin/bash pyenv.run
